const tabs=['Dashboard','Sell','Quote','Purchase','Stock','Masters','Reports','Import / Export'];
const key='tagro-echo-os-prototype-v1';
const fresh=()=>({users:[],branches:[],products:[],prices:[],customers:[],suppliers:[],quotes:[],sales:[],purchases:[],stockMovements:[]});
let state=(()=>{try{return JSON.parse(localStorage.getItem(key))||fresh()}catch{return fresh()}})();
let active='Dashboard';
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const id=p=>p+'-'+crypto.getRandomValues(new Uint32Array(1))[0].toString(16); const save=()=>localStorage.setItem(key,JSON.stringify(state));
const product=x=>state.products.find(p=>p.product_id===x); const branch=x=>state.branches.find(p=>p.branch_id===x);
const priceOf=x=>{const rows=state.prices.filter(p=>p.product_id===x&&p.price_type==='mrp').sort((a,b)=>String(b.effective_from).localeCompare(String(a.effective_from)));return Number(rows[0]?.amount||0)};
const stock=(b,p)=>state.stockMovements.filter(x=>x.branch_id===b&&x.product_id===p).reduce((a,x)=>a+Number(x.quantity_delta),0);
const total=t=>t.items.reduce((a,x)=>a+(Number(x.qty)*Number(x.unit_price))*(1+Number(x.gst_rate)/100),0);
function renderNav(){ $('#nav').innerHTML=tabs.map(t=>`<button data-tab="${t}" class="${t===active?'active':''}">${t}</button>`).join(''); document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{active=b.dataset.tab;render()}) }
function render(){renderNav(); const views={'Dashboard':dashboard,'Sell':()=>transaction('sale'),'Quote':()=>transaction('quote'),'Purchase':()=>transaction('purchase'),'Stock':stockView,'Masters':masters,'Reports':reports,'Import / Export':ioView}; $('#app').innerHTML=`<div class="notice"><b>Local prototype.</b> Operational semantics are being tested here; production persistence is not yet connected.</div>`+views[active](); bind()}
function metric(k,v){return `<div class="card metric"><span class="muted">${k}</span><strong>${v}</strong></div>`}
function dashboard(){return `<h1>Today</h1><div class="grid">${metric('Counters',state.branches.length)}${metric('Products',state.products.length)}${metric('Quotes',state.quotes.length)}${metric('Sales',state.sales.length)}${metric('Purchases',state.purchases.length)}${metric('Customers',state.customers.length)}</div><div class="card" style="margin-top:14px"><h3>Operating model</h3><p>Counter activity originates here. BUSY will receive governed accounting exports later; it is not required to create the operational record.</p></div>`}
function opts(arr,idf,label){return arr.map(x=>`<option value="${esc(x[idf])}">${esc(label(x))}</option>`).join('')}
function transaction(kind){const isP=kind==='purchase'; const party=isP?'supplier':'customer'; const parties=isP?state.suppliers:state.customers; const partyId=isP?'supplier_id':'customer_id';return `<h1>${kind[0].toUpperCase()+kind.slice(1)}</h1><div class="card"><div class="row"><label>Counter<select id="txBranch"><option value="">Select</option>${opts(state.branches,'branch_id',x=>x.code+' · '+x.name)}</select></label><label>${party}<select id="txParty"><option value="">Select</option>${opts(parties,partyId,x=>x.name)}</select></label></div><div class="row"><label>Product<select id="txProduct"><option value="">Select</option>${opts(state.products,'product_id',x=>x.model+' · '+x.name)}</select></label><label>Qty<input id="txQty" type="number" min="0.01" step="0.01" value="1"></label><label>Unit price<input id="txPrice" type="number" min="0" step="0.01"></label></div><div class="actions"><button class="orange" id="createTx">Create ${kind}</button></div><p class="muted">${kind==='sale'?'Stock is checked before the sale is admitted.':''}</p></div><h2>Recent</h2>${txTable(kind)}`}
function txTable(kind){const arr=state[kind==='sale'?'sales':kind==='quote'?'quotes':'purchases'];return `<table><tr><th>ID</th><th>Counter</th><th>Total</th><th>Time</th></tr>${arr.slice().reverse().map(x=>`<tr><td>${esc(x.id)}</td><td>${esc(branch(x.branch_id)?.code||x.branch_id)}</td><td>₹${total(x).toFixed(2)}</td><td>${esc(x.created_at)}</td></tr>`).join('')}</table>`}
function stockView(){return `<h1>Stock</h1><div class="card"><div class="row"><label>Counter<select id="stBranch"><option value="">Select</option>${opts(state.branches,'branch_id',x=>x.code+' · '+x.name)}</select></label><label>Product<select id="stProduct"><option value="">Select</option>${opts(state.products,'product_id',x=>x.model)}</select></label><label>Adjustment<input id="stDelta" type="number" step="0.01"></label></div><label>Reason<input id="stNote" placeholder="Required for manual adjustment"></label><div class="actions"><button id="adjustStock">Record adjustment</button></div></div><h2>Position</h2><table><tr><th>Counter</th><th>Product</th><th>Qty</th></tr>${state.branches.flatMap(b=>state.products.map(p=>({b,p,q:stock(b.branch_id,p.product_id)}))).filter(x=>x.q!==0).map(x=>`<tr><td>${esc(x.b.code)}</td><td>${esc(x.p.model)}</td><td>${x.q}</td></tr>`).join('')}</table>`}
const masterDefs={branches:['branch_id','code','name','district'],users:['user_id','name','email','role','branch_id'],products:['product_id','sku','model','name','category','gst_rate'],prices:['price_id','product_id','price_type','amount','effective_from'],customers:['customer_id','name','phone','email'],suppliers:['supplier_id','name','phone','email']};
function masters(){return `<h1>Masters</h1><div class="grid">${Object.keys(masterDefs).map(n=>`<div class="card"><h3>${n}</h3><strong>${state[n].length}</strong><div class="actions"><button data-master="${n}">Add</button></div></div>`).join('')}</div><div id="masterForm"></div>`}
function masterForm(name){const fields=masterDefs[name];return `<div class="card" style="margin-top:14px"><h2>Add ${name.slice(0,-1)}</h2><div class="row">${fields.map(f=>`<label>${f}<input data-mf="${f}" ${f.endsWith('_id')?'placeholder="leave blank to generate"':''}></label>`).join('')}</div><div class="actions"><button class="orange" id="saveMaster" data-name="${name}">Save</button></div></div>`}
function reports(){const sales=state.sales.reduce((a,x)=>a+total(x),0), purchases=state.purchases.reduce((a,x)=>a+total(x),0), quotes=state.quotes.reduce((a,x)=>a+total(x),0);return `<h1>Reports</h1><div class="grid">${metric('Sales value','₹'+sales.toFixed(2))}${metric('Purchase value','₹'+purchases.toFixed(2))}${metric('Quote pipeline','₹'+quotes.toFixed(2))}${metric('Stock movements',state.stockMovements.length)}</div><h2>Counter summary</h2><table><tr><th>Counter</th><th>Sales</th><th>Stock units</th></tr>${state.branches.map(b=>`<tr><td>${esc(b.code)} · ${esc(b.name)}</td><td>₹${state.sales.filter(x=>x.branch_id===b.branch_id).reduce((a,x)=>a+total(x),0).toFixed(2)}</td><td>${state.products.reduce((a,p)=>a+stock(b.branch_id,p.product_id),0)}</td></tr>`).join('')}</table>`}
const fields={users:['user_id','name','email','role','branch_id','active'],branches:['branch_id','code','name','district','branch_type','active'],products:['product_id','sku','model','name','category','gst_rate','unit','serial_tracked','active'],prices:['price_id','product_id','price_type','amount','effective_from','effective_to','branch_id'],customers:['customer_id','name','phone','email','gstin','district'],suppliers:['supplier_id','name','phone','email','gstin']};
function csv(name){const f=fields[name], rows=state[name];return [f.join(','),...rows.map(r=>f.map(k=>'"'+String(r[k]??'').replaceAll('"','""')+'"').join(','))].join('\n')}
function ioView(){return `<h1>Import / Export</h1><div class="card"><p>These canonical lists keep ECHO operations independent of BUSY. Later adapters can import/export these contracts.</p><div class="row"><label>Dataset<select id="ioDataset">${Object.keys(fields).map(x=>`<option>${x}</option>`).join('')}</select></label><label>CSV file<input id="ioFile" type="file" accept=".csv,text/csv"></label></div><div class="actions"><button id="exportCsv">Export CSV</button><button class="ghost" id="importCsv">Import CSV</button></div><p class="muted">Imports require exact headers and are intended for controlled master-data loading in this prototype.</p></div>`}
function bind(){document.querySelectorAll('[data-master]').forEach(b=>b.onclick=()=>{$('#masterForm').innerHTML=masterForm(b.dataset.master);bind()}); const sm=$('#saveMaster'); if(sm)sm.onclick=saveMaster; const cp=$('#txProduct'); if(cp)cp.onchange=()=>{$('#txPrice').value=priceOf(cp.value)||''}; const ct=$('#createTx'); if(ct)ct.onclick=createTx; const as=$('#adjustStock');if(as)as.onclick=adjustStock; const ex=$('#exportCsv');if(ex)ex.onclick=exportCsv; const im=$('#importCsv');if(im)im.onclick=importCsv}
function saveMaster(e){const name=e.target.dataset.name, r={};document.querySelectorAll('[data-mf]').forEach(i=>r[i.dataset.mf]=i.value.trim()); const idf=masterDefs[name][0];if(!r[idf])r[idf]=id(name.slice(0,3)); if(name==='products'){r.gst_rate=Number(r.gst_rate||18);r.unit='nos';r.serial_tracked=false;r.active=true}if(name==='branches'){r.branch_type='counter';r.active=true}if(name==='users')r.active=true;if(name==='prices')r.effective_to='';state[name].push(r);save();render()}
function createTx(){const kind=active.toLowerCase(),b=$('#txBranch').value,pid=$('#txProduct').value,party=$('#txParty').value,qty=Number($('#txQty').value),unit=Number($('#txPrice').value),p=product(pid);if(!b||!pid||!party||qty<=0||unit<0)return alert('Complete branch, party, product, quantity and price.');if(kind==='sale'&&stock(b,pid)<qty)return alert('Insufficient stock.');const rec={id:id(kind.slice(0,3)),branch_id:b,created_at:new Date().toISOString(),items:[{product_id:pid,qty,unit_price:unit,gst_rate:Number(p.gst_rate||0)}]};if(kind==='purchase'){rec.supplier_id=party;state.purchases.push(rec);state.stockMovements.push({movement_id:id('stk'),branch_id:b,product_id:pid,quantity_delta:qty,movement_type:'purchase',occurred_at:rec.created_at,reference_type:'purchase',reference_id:rec.id,note:''})}else if(kind==='quote'){rec.customer_id=party;state.quotes.push(rec)}else{rec.customer_id=party;rec.payment_status='unpaid';state.sales.push(rec);state.stockMovements.push({movement_id:id('stk'),branch_id:b,product_id:pid,quantity_delta:-qty,movement_type:'sale',occurred_at:rec.created_at,reference_type:'sale',reference_id:rec.id,note:''})}save();render()}
function adjustStock(){const b=$('#stBranch').value,p=$('#stProduct').value,d=Number($('#stDelta').value),n=$('#stNote').value.trim();if(!b||!p||!d||!n)return alert('Counter, product, non-zero quantity and reason are required.');if(stock(b,p)+d<0)return alert('Adjustment would make stock negative.');state.stockMovements.push({movement_id:id('stk'),branch_id:b,product_id:p,quantity_delta:d,movement_type:'adjustment',occurred_at:new Date().toISOString(),reference_type:'manual_adjustment',reference_id:id('adj'),note:n});save();render()}
function exportCsv(){const n=$('#ioDataset').value,blob=new Blob([csv(n)],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=n+'.csv';a.click();URL.revokeObjectURL(a.href)}
function importCsv(){const n=$('#ioDataset').value,f=$('#ioFile').files[0];if(!f)return alert('Choose a CSV file.');f.text().then(t=>{const lines=t.trim().split(/\r?\n/),head=lines.shift().split(',').map(x=>x.replace(/^"|"$/g,''));if(head.join('|')!==fields[n].join('|'))return alert('Header does not match canonical '+n+' contract.');const rows=lines.filter(Boolean).map(line=>{const vals=line.match(/("(?:[^"]|"")*"|[^,]*)(?:,|$)/g).map(x=>x.replace(/,$/,'').replace(/^"|"$/g,'').replaceAll('""','"'));return Object.fromEntries(head.map((h,i)=>[h,vals[i]??'']))});state[n].push(...rows);save();render()})}
render();
