(()=>{'use strict';
const $=id=>document.getElementById(id);let hideTimer=null;
function toast(message){const el=$('toast');if(!el)return;el.textContent=message;el.classList.remove('hidden');clearTimeout(hideTimer);hideTimer=setTimeout(()=>el.classList.add('hidden'),2200)}
function initials(value){const s=String(value||'ECHO').trim(),name=s.includes('@')?s.split('@')[0]:s;return name.split(/[._\s-]+/).filter(Boolean).slice(0,2).map(x=>x[0]?.toUpperCase()).join('')||'E'}
function updateNetwork(){const online=navigator.onLine;$('networkState')?.classList.toggle('offline',!online);if($('networkLabel'))$('networkLabel').textContent=online?'Online':'Offline';updateQueue()}
function updateQueue(){if(!window.EchoRuntime)return;try{const pending=EchoRuntime.pendingQueue().length,review=EchoRuntime.reviewQueue().length;if($('pendingText'))$('pendingText').textContent=pending?`${pending} ${pending===1?'record':'records'} waiting`:'Nothing waiting';if($('reviewText'))$('reviewText').textContent=review?`${review} ${review===1?'item':'items'} to review`:'No local review items';if($('truthLine'))$('truthLine').textContent=navigator.onLine?(pending?'Online · saved work still waiting for ECHO':'Online · work is up to date'):(pending?`Offline · ${pending} saved locally`:'Offline · no work waiting to send')}catch{if($('pendingText'))$('pendingText').textContent='Sign in to view';if($('reviewText'))$('reviewText').textContent='Sign in to view'}}
function findMembership(ctx,id){const ents=Array.isArray(ctx?.enterprises)?ctx.enterprises:[];return ents.find(x=>x.enterprise_id===id)||ents[0]||null}
function applyCapabilities(membership){const caps=new Set(Array.isArray(membership?.capabilities)?membership.capabilities:[]);if(!caps.size)return;document.querySelectorAll('[data-capability]').forEach(el=>el.classList.toggle('hidden',!caps.has(el.getAttribute('data-capability'))))}
async function loadDataState(){if(!$('dataState'))return;try{const s=await EchoRuntime.request('/db-health');$('dataState').textContent=s?.status==='database_reachable'?'Shared business data ready':'Business data unavailable'}catch{$('dataState').textContent='Business data temporarily unavailable'}}
async function load(){if(!window.EchoRuntime){$('person').textContent='ECHO unavailable';$('place').textContent='Refresh or check connection';return}const info=EchoRuntime.sessionInfo();if(!info.signedIn){location.href='login.html';return}$('avatar').textContent=initials(info.email);$('person').textContent=info.email||'Signed-in staff';$('place').textContent='Resolving workspace…';updateQueue();try{const ctx=await EchoRuntime.loadContext(),selected=EchoRuntime.sessionInfo().enterpriseId,m=findMembership(ctx,selected);if(m){const name=ctx.display_name||info.email||'Staff',role=m.role_code||'Staff',enterprise=m.enterprise_code||m.enterprise_name||'ECHO';$('person').textContent=`${name} · ${String(role).replaceAll('_',' ')}`;$('place').textContent=enterprise;$('roleTitle').textContent=String(role).toUpperCase().includes('OWNER')?'OWNER WORK':'WORK';applyCapabilities(m)}else{$('place').textContent=selected?'Workspace selected':'Workspace unavailable'}await loadDataState()}catch{$('place').textContent='Workspace temporarily unavailable';$('dataState').textContent='Business data temporarily unavailable';toast('Your signed-in session is retained.')}}
$('quick')?.addEventListener('click',()=>location.href='billing.html');
$('menu')?.addEventListener('click',()=>toast('More tools will appear here only when they are ready for use.'));
$('pendingCard')?.addEventListener('click',e=>{e.preventDefault();updateQueue();toast($('pendingText')?.textContent||'No work waiting')});
addEventListener('online',updateNetwork);addEventListener('offline',updateNetwork);addEventListener('echo:queue-updated',updateQueue);updateNetwork();load();
})();
